services:
  converter:
    build:
      context: .
      dockerfile: dev.Dockerfile
      target: dev
    restart: always
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: dev
    volumes:
      - ./:/src/dev
#      - /home/teller/media/photos:/original
      - ~/projects/media-converter/original:/original
