version: "3.6"
services:
  converter:
    build:
      context: .
      dockerfile: dev.Dockerfile
      target: dev
    restart: always
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: dev
    volumes:
      - ./:/src/dev
      - /home/teller/media/converter/original:/original
      - /home/teller/media/converter/converted:/converted
    networks:
      - converter_network

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    hostname: rabbitmq
    volumes:
      - /var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 15s
      retries: 3
    networks:
      - converter_network

  minio:
    container_name: minio
    image: quay.io/minio/minio:latest
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: 'accessKey'
      MINIO_ROOT_PASSWORD: 'secretKey'
    volumes:
      - /home/teller/media/converter/minio:/data
    command: server /data --console-address ":9001"
    networks:
      - converter_network

networks:
  converter_network:
    driver: bridge
